### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by analtrivedi** [google/android-uiconductor#3]
I am unable to install uiConductor due to below error.

 _**problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.**_

But I already set SDK path on sdk.dir in the local.properties file. I also set env path on ~/.bashrc file. ADB command is working properly.   

Please suggest me how to resolve this issue.

**Comment by tccyp001** [comment]
where is your  android sdk, can you try: 
echo $ANDROID_HOME
you should see something like:
/usr/local/xxx/Android/Sdk

**Comment by analtrivedi** [comment]
Hi,

Sorry for late reply.

As per your suggestion I used below command but its showing empty.
Command: "echo $ANDROID_HOME"

Could you suggest me how to set android sdk home path properly.

Best regards,
Anal Trivedi

**Comment by analtrivedi** [comment]
Hi, 

I Solved ANDROID_HOME related issue and able to build successfully.

But after getting **BUILD successful** message its showing below error.

Error Log:
**[INFO] --- spring-boot-maven-plugin:1.5.7.RELEASE:repackage (default) @ uicd-service ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.715s
[INFO] Finished at: Mon Feb 18 19:29:52 JST 2019
[INFO] Final Memory: 37M/531M
[INFO] ------------------------------------------------------------------------
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: asap@2.0.6 (node_modules/asap):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/asap/-/asap-2.0.6.tgz failed, reason: write EPROTO 139682844190592:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 

npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@ngtools/json-schema/-/json-schema-1.2.0.tgz failed, reason: write EPROTO 139682844190592:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/CORPUSERS/xp023850/.npm/_logs/2019-02-18T10_29_56_996Z-debug.log**

I think this is Angular CLI setup related error..

If you have any information about this error then please share with us...

**Comment by tccyp001** [comment]
Please make sure node and angular is the following version
Angular CLI: 1.7.4 
Node: 10.15.0

Please let me know if you still have issue build it, I can provider a release version here, so that you don't need build or anything.

**Comment by analtrivedi** [comment]
It was proxy related issue and now it has been solved. I am able to build successfully and launched UIConductor using "start.sh" script.
But unfortunately the device is not getting connected with UIConductor(Not showing device screen on UIConductor). Please check below for system setup details & back end launching logs.   

**Setup Details:**
_1. Node JS Installed_
$ node -v
v10.15.1

_2. Angular CLI Installed_
Your global Angular CLI version (7.3.2) is greater than your local
version (1.7.4). The local Angular CLI version is used.

_3. Device Connect_
$ adb devices
List of devices attached
BH9300F8D4	device
Removed password or pattern lock.

_4.Create mysql database._ 
Create an empty database schema called "uicddb" - Done
Execute backend/src/com/google/uicd/backend/recorder/db/initdb.sql to init the database schema. -Done

$ mysql> desc uicddb.uicd_testcase;
+-------------+--------------+------+-----+-------------------+-------+
| Field       | Type         | Null | Key | Default           | Extra |
+-------------+--------------+------+-----+-------------------+-------+
| uuid        | varchar(60)  | NO   | PRI | NULL              |       |
| type        | varchar(60)  | NO   | MUL | NULL              |       |
| name        | varchar(100) | NO   |     | NULL              |       |
| tag         | varchar(200) | NO   |     | NULL              |       |
| description | varchar(500) | NO   |     | NULL              |       |
| details     | blob         | YES  |     | NULL              |       |
| created_by  | varchar(50)  | NO   |     | NULL              |       |
| created_at  | timestamp    | NO   |     | CURRENT_TIMESTAMP |       |
+-------------+--------------+------+-----+-------------------+-------+


**Launch UIConductor**

$ cd release/
$ ./start.sh

================================= Launch Backend ================================================
List of devices attached
BH9300F8D4	device

Font Name: Doh
  UUUUUUUU     UUUUUUUUIIIIIIIIII      CCCCCCCCCCCCCDDDDDDDDDDDDD
  U::::::U     U::::::UI::::::::I   CCC::::::::::::CD::::::::::::DDD
  U::::::U     U::::::UI::::::::I CC:::::::::::::::CD:::::::::::::::DD
  UU:::::U     U:::::UUII::::::IIC:::::CCCCCCCC::::CDDD:::::DDDDD:::::D
   U:::::U     U:::::U   I::::I C:::::C       CCCCCC  D:::::D    D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U:::::D     D:::::U   I::::IC:::::C                D:::::D     D:::::D
   U::::::U   U::::::U   I::::I C:::::C       CCCCCC  D:::::D    D:::::D
   U:::::::UUU:::::::U II::::::IIC:::::CCCCCCCC::::CDDD:::::DDDDD:::::D
    UU:::::::::::::UU  I::::::::I CC:::::::::::::::CD:::::::::::::::DD
      UU:::::::::UU    I::::::::I   CCC::::::::::::CD::::::::::::DDD
        UUUUUUUUU      IIIIIIIIII      CCCCCCCCCCCCCDDDDDDDDDDDDD

2019-02-20 16:10:47.284  INFO 2153 --- [           main] com.google.uicd.backend.app.Application  : Starting Application v0.1.0 on jptolx26274 with PID 2153 (/home/CORPUSERS/xp023850/UIConductor/Set2/android-uiconductor-master/release/uicd-service-0.1.0.jar started by xp023850 in /home/CORPUSERS/xp023850/UIConductor/Set2/android-uiconductor-master/release)
2019-02-20 16:10:47.287  INFO 2153 --- [           main] com.google.uicd.backend.app.Application  : No active profile set, falling back to default profiles: default
2019-02-20 16:10:47.338  INFO 2153 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5cb0d902: startup date [Wed Feb 20 16:10:47 JST 2019]; root of context hierarchy
2019-02-20 16:10:48.510  INFO 2153 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8089 (http)
2019-02-20 16:10:48.521  INFO 2153 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-02-20 16:10:48.522  INFO 2153 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.20
2019-02-20 16:10:48.584  INFO 2153 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-02-20 16:10:48.584  INFO 2153 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1248 ms
2019-02-20 16:10:48.685  INFO 2153 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2019-02-20 16:10:48.688  INFO 2153 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2019-02-20 16:10:48.689  INFO 2153 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-02-20 16:10:48.689  INFO 2153 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-02-20 16:10:48.689  INFO 2153 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2019-02-20 16:10:48.732  INFO 2153 --- [           main] o.s.j.d.DriverManagerDataSource          : Loaded JDBC driver: com.mysql.jdbc.Driver
**Cannot connect to Mysql**
2019-02-20 16:10:52.919  WARN 2153 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workflowManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Connection must not be null
2019-02-20 16:10:52.920  INFO 2153 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-02-20 16:10:52.929  INFO 2153 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-02-20 16:10:52.935 ERROR 2153 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workflowManager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Connection must not be null
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
	at com.google.uicd.backend.app.Application.main(Application.java:48) [classes!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [uicd-service-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [uicd-service-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [uicd-service-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [uicd-service-0.1.0.jar:0.1.0]
Caused by: java.lang.IllegalArgumentException: Connection must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.jdbc.datasource.SingleConnectionDataSource.<init>(SingleConnectionDataSource.java:115) ~[spring-jdbc-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at com.google.uicd.backend.core.db.ActionDAO.<init>(ActionDAO.java:43) ~[classes!/:0.1.0]
	at com.google.uicd.backend.core.db.ActionStorageManager.init(ActionStorageManager.java:311) ~[classes!/:0.1.0]
	at com.google.uicd.backend.core.db.ActionStorageManager.<init>(ActionStorageManager.java:49) ~[classes!/:0.1.0]
	at com.google.uicd.backend.recorder.workflowmgr.WorkflowManager.init(WorkflowManager.java:487) ~[classes!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	... 26 common frames omitted

================================= Launch Frontend ================================================
[2186:2186:0220/161056.836465:ERROR:browser_dm_token_storage_linux.cc(93)] Error: /etc/machine-id contains 32 characters (32 were expected).
[2186:2186:0220/161056.836707:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[2186:2186:0220/161056.898184:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy: EnableCommonNameFallbackForLocalAnchors
[2223:2223:0220/161056.901248:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
[2186:2186:0220/161056.967058:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

**Comment by tccyp001** [comment]
it says "Cannot connect to Mysql"
have you setup the mysql in your local? Please follow the instruction in read me.

**Comment by analtrivedi** [comment]
Yes I already changed.

Installation:
5. Set the db connection string in the release/uicd.cfg to something like this: jdbc:mysql://localhost:3306/uicddb?autoReconnect=true&user=root&password=admin&useUnicode=true&characterEncoding=utf-8 Please make sure change the username and password to your own username and password.
> Done..
Also I am able to access mysql using my credentials from terminal.

$ mysql -u USERID -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5727
...........
mysql>

**Comment by tccyp001** [comment]
you replaced the user=root and password right?

**Comment by analtrivedi** [comment]
Yes I checked it. As per your instructions I already modified[changed user & password] in "uicd.cfg" file.

**Comment by tccyp001** [comment]
not sure, you can use intellij to open the backend and try to debug.

**Comment by analtrivedi** [comment]
Tried without quote also but getting same error.

**Comment by tccyp001** [comment]
I think it might be your maven setup issue?
what is your mysql version? can you run  "mvn dependency:tree" to see the dependency for the backend project?
do you see mysql:mysql-connector-java:jar:5.1.6:compil?

**Comment by analtrivedi** [comment]
Yes you are correct. I checked dependency:tree and found mysql-connector jar version is 5.1.6
[INFO] +- mysql:mysql-connector-java:jar:5.1.6:compile

So do I need to upgrade mysql version or I need to modify "mysqlconnectionstr" string format that will support my existing mysql-connector jar version.

I have Ubuntu 14.04 OS in my system.

**Comment by tccyp001** [comment]
you should have the currect version of mysql connector. not sure why, what is your mysql version?

**Comment by tccyp001** [comment]
can you debug what is getDBConnStr() return?

**Comment by analtrivedi** [comment]
**getDBConnStr() return **
ConnString> jdbc:mysql://localhost:3308/uicddb?autoReconnect=true&user=root&password=uicdawesome&useUnicode=true&characterEncoding=utf-8

$ mysql --version
mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3

**mysql connector:**
/usr/share/java/mysql-connector-java-5.1.28.jar

Below command I used to installed connector:
sudo apt-get install libmysql-java

**Comment by tccyp001** [comment]
is it because the port should be 3306 instead of 3308?

**Comment by analtrivedi** [comment]
I found the the problem. getDBConnStr() method of UicdConfig.java returned hard coded connection string. Because maybe "mysqlConnectionSting" is null or empty. So in initDefaultLocalDBConnection method I modified connection string manually as below and build it again. After that its working fine.

```
public void initDefaultLocalDBConnection() throws UicdExcpetion {
    try {
      String TempStr = "jdbc:mysql://localhost:3306/uicddb?autoReconnect=true&user=root&password=zero&useUnicode=true&characterEncoding=utf-8";
      connection =
          DriverManager.getConnection(TempStr);
    } catch (SQLException e) {
      throw new UicdExcpetion("Cannot connect to Mysql");
    }
  }  
```

Thanks for your help & support. :-)
